### ISSUE TITLE
Single comic, array value

### ISSUE THREAD

**Issue by jbehrens94** [victorpimentel/MarvelAPI#1]
Hi!

Any reason why for this endpoint, still an array of comics is the response type?

https://github.com/victorpimentel/MarvelAPI/blob/2b247f37b2a74763db86463ed4345c2a2ab95bd8/MarvelAPI.playground/Sources/Requests/GetComic.swift#L4

**Comment by victorpimentel** [comment]
That's how the API works, it returns an array inside a data object:

https://developer.marvel.com/docs#!/public/getComicIndividual_get_7

```
{
  "code": "int",
  "status": "string",
  "data": {
    "offset": "int",
    "limit": "int",
    "total": "int",
    "count": "int",
    "results": [
      {
        "id": "int",
        ...
      }
    ]
  },
  ...
}
```

That API is incredibly consistent.
